import type { AppProps } from 'next/app'
import Head from 'next/head'

import Footer from '../components/Footer/Footer'
import '../styles/global.css'

function MyApp({ Component, pageProps }: AppProps): JSX.Element {
  return (
    <>
      <Head>
        <title>Contentstack - Next.js</title>
        <meta name="description" content="Generated by Federico Orlandau" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
      <Footer />
    </>
  )
}

export default MyApp
