import type { AppProps } from 'next/app'
import Head from 'next/head'

import Footer from '../components/Footer/Footer'
import { Header } from '../components/Header'
import '../styles/global.css'

function MyApp({ Component, pageProps }: AppProps): JSX.Element {
  const page = pageProps.page;
  const headerProps =
    page && page.header && page.header.length ? page.header[0] : null;
  const footerProps =
    page && page.footer && page.footer.length ? page.footer[0] : null;

  console.log()
  return (
    <>
      <Head>
        <title>Contentstack - Next.js</title>
        <meta name="description" content="Generated by Federico Orlandau" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header {...headerProps} />
      <Component {...pageProps} />
      <Footer {...footerProps} />
    </>
  )
}

export default MyApp
